name: "hello world workflow"
on:
  push:
    branches:
      - master
      - production
  
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "print hello world"
        run: echo "hello world"
    
      - name: "print date"
        run: date
