name: "multi-event workflow"

on:
  push:
    branches: 
      - master
      - test
  pull_request: 
    branches: 
      - master
    
jobs:
  on_push:
    if : github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "push is triggered"
        run: echo "push push push push "
  on_pull-request:
    if : github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "pull request is triggered"
        run: echo "pull pull pull pull "
